version: '3.8'

services:
  mongodb:
    image: mongo:6.0-alpine
    container_name: weather-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: weather-app
    networks:
      - weather-network

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: weather-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/weather-app
      - PORT=5000
      - NODE_ENV=production
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    depends_on:
      - mongodb
    networks:
      - weather-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: weather-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:5000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - weather-network

volumes:
  mongodb_data:

networks:
  weather-network:
    driver: bridge