services:
  # Backend API Service
  - type: web
    name: weather-app-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: MONGODB_URI
        fromDatabase:
          name: weather-app-db
          property: connectionString
    healthCheckPath: /api/health

  # Frontend Service
  - type: web
    name: weather-app-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_BASE_URL
        value: https://weather-app-backend.onrender.com/api

databases:
  # MongoDB Database
  - name: weather-app-db
    plan: free
    databaseName: weather-app
    user: weatherapp
